name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}

          script: |
            cd /home/ubuntu/6weeks_manjot_MEAN
            git pull origin main
            npm i
            npm i pm2 -g
            npm i -g http-server
            npm run build
            pm2 start http-server --name frontend -- dist/bicycle -p 3015
