name: deploy
on:
  push: 
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy to EC2 via SSH 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PRIVATE_key}}

          script: |
            cd /home/ubuntu/6weeks_manjot_MEAN
            git pull origin main
            npm i
            npm i pm2 -g
            npm run build 
            pm2 start http-server --name frontend -- dist/bicycle -p 3015
      
